/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ApiRemainingDotjsonRouteImport } from './routes/api/remaining[.]json'
import { Route as ApiSummaryDotjsonRouteImport } from './routes/api/summary[.]json'
import { Route as ApiTreeDotjsonRouteImport } from './routes/api/tree[.]json'
import { Route as ApiPartiesIdRouteImport } from './routes/api/parties/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemainingDotjsonRoute = ApiRemainingDotjsonRouteImport.update({
  id: '/api/remaining.json',
  path: '/api/remaining.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryDotjsonRoute = ApiSummaryDotjsonRouteImport.update({
  id: '/api/summary.json',
  path: '/api/summary.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTreeDotjsonRoute = ApiTreeDotjsonRouteImport.update({
  id: '/api/tree.json',
  path: '/api/tree.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartiesIdRoute = ApiPartiesIdRouteImport.update({
  id: '/api/parties/$id',
  path: '/api/parties/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/remaining.json': typeof ApiRemainingDotjsonRoute
  '/api/summary.json': typeof ApiSummaryDotjsonRoute
  '/api/tree.json': typeof ApiTreeDotjsonRoute
  '/api/parties/$id': typeof ApiPartiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/remaining.json': typeof ApiRemainingDotjsonRoute
  '/api/summary.json': typeof ApiSummaryDotjsonRoute
  '/api/tree.json': typeof ApiTreeDotjsonRoute
  '/api/parties/$id': typeof ApiPartiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/remaining.json': typeof ApiRemainingDotjsonRoute
  '/api/summary.json': typeof ApiSummaryDotjsonRoute
  '/api/tree.json': typeof ApiTreeDotjsonRoute
  '/api/parties/$id': typeof ApiPartiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/api/remaining.json'
    | '/api/summary.json'
    | '/api/tree.json'
    | '/api/parties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/api/remaining.json'
    | '/api/summary.json'
    | '/api/tree.json'
    | '/api/parties/$id'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/api/remaining.json'
    | '/api/summary.json'
    | '/api/tree.json'
    | '/api/parties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiRemainingDotjsonRoute: typeof ApiRemainingDotjsonRoute
  ApiSummaryDotjsonRoute: typeof ApiSummaryDotjsonRoute
  ApiTreeDotjsonRoute: typeof ApiTreeDotjsonRoute
  ApiPartiesIdRoute: typeof ApiPartiesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remaining.json': {
      id: '/api/remaining.json'
      path: '/api/remaining.json'
      fullPath: '/api/remaining.json'
      preLoaderRoute: typeof ApiRemainingDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary.json': {
      id: '/api/summary.json'
      path: '/api/summary.json'
      fullPath: '/api/summary.json'
      preLoaderRoute: typeof ApiSummaryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tree.json': {
      id: '/api/tree.json'
      path: '/api/tree.json'
      fullPath: '/api/tree.json'
      preLoaderRoute: typeof ApiTreeDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parties/$id': {
      id: '/api/parties/$id'
      path: '/api/parties/$id'
      fullPath: '/api/parties/$id'
      preLoaderRoute: typeof ApiPartiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiRemainingDotjsonRoute: ApiRemainingDotjsonRoute,
  ApiSummaryDotjsonRoute: ApiSummaryDotjsonRoute,
  ApiTreeDotjsonRoute: ApiTreeDotjsonRoute,
  ApiPartiesIdRoute: ApiPartiesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
